In [1]:
import torch
import pandas as pd

In [6]:
df_relaxase_raw = pd.read_csv("../data/processed/cleaned_datasets/relaxase_oriT_dataset.csv")

df_relax = df_relaxase_raw.dropna(subset=['oriT_nic_seq'])

df_relax = df_relax.drop(columns=['oriTDB_accession', 'oriTDB_id', 'nic site', 'host', 'sDBM_sim_gap', 'relaxase_family'])

df_relax = df_relax[["sDBM_pos", "sDBM", "oriT_nic_seq", "relaxase_sequence"]]

df_relax.rename(columns={"sDBM_pos": "sDBM_pos", "sDBM": "sDBM", "oriT_nic_seq": "ori_nic_seq", "relaxase_sequence": "amino_acid_seq"}, inplace=True)

df_relax

,sDBM_pos,sDBM,ori_nic_seq,amino_acid_seq
0,"(4, 12)",HVPMRSIKK,TATCCTGCC,MIAKHVPMRSIKKSDFAELVKYITDEQGKTERLGHVRVTNCEANTL...
1,"(4, 12)",HLTAKTGSR,AAGTGCGCC,MAIYHLTAKTGSRSGGQSARAKADYIQREGKYARDMDEVLHAESGH...
2,"(4, 12)",VEKDYRVKR,TATCCTGCA,MGVFVEKDYRVKRKSSENGRKSAFAHKVKNGGENYKKNVREKINRK...
3,"(2, 10)",IAKRENGKR,AAGTGCGCC,MTIAKRENGKRSLIAMASYRSGEKLYSELYEKTNLYNHRTVKPEAF...
4,"(2, 10)",SISSIKGDA,CGGGTGTGG,MLSISSIKGDAGYYSHEDNYYASGSLDSRWMGEGAEKLGLKGEVAS...
...,...,...,...,...
223,"(24, 32)",TIVGNLNKN,TCGATTGGT,MYSNSRLSGQTLGKSQPELSFDAMTIVGNLNKNNAQKLSEFMSVEP...
224,"(4, 12)",VARTEKRKV,TAGCTTGCA,MAFMVARTEKRKVGSLAGYQNHVDRKTENHSNKEIDKSKTFLNYDL...
225,"(8, 16)",YLQNKDLDN,TCGATTGGT,MSTENYSNYLQNKDLDNFSKTGYSNSRLDAHTVCISKPKISFDAMT...
226,"(6, 14)",VLVSKYVSG,TTTATGGTT,MDAPGVVLVSKYVSGKSTKFSKYVNYINRDEAVRTEKFQTYNVNKL...
227,"(2, 10)",SKHIRNPDA,GGGGTGTGG,MISKHIRNPDAKAAKHRRIIKLVEYILNPQTESATEKCVYHGARGF...

In [5]:
df_rep = pd.read_csv("../data/processed/unique_rep_oriR_dataset.csv")

df_rep.rename(columns={"sDBM_pos": "sDBM_pos", "sDBM": "sDBM", "ori_seq": "ori_nic_seq", "rep_amino_acid_seq": "amino_acid_seq"}, inplace=True)

df_rep

,sDBM_pos,sDBM,ori_nic_seq,amino_acid_seq
0,"(63, 71)",GAHFEKRRG,TAGTATTAC,MARQVICWCFTLNNPLSPLSLHDSMKYLVYQTEQGEAGNIHFQGYI...
1,"(63, 71)",GAHLEKRKG,TATTATTAC,MARYVVCWMFTINNPSSLPVMRDEIKYMVYQVERGQEGTRHVQGYV...
2,"(73, 81)",KPHLEKQRA,GACTGCTAC,MAAIKGQWWCFTVFFLTATAPDLVPLFENTHVSYACWQEEESPTTK...
3,"(70, 78)",RAHWEKARG,TAGTATTAC,MSASRWTFTLHYSDATERGKFLATLKEEDVHYAVVGDETAPNTGRK...
4,"(74, 82)",RAHFECAKG,CAGTATTAC,MAPRGNAAKRWTFTINNWTLADYDKVLEFTTKFEPVFLICGKERGE...
...,...,...,...,...
224,"(64, 72)",QAHIEESNH,TAGTAATAC,MKVYLITAPRSTPKKALKIMIEKNDCKKWIIGWEKGKNGYEHFQIR...
225,"(64, 72)",AAHIEEAQQ,CATTTGTAC,MKKYIMTVPRSVPKKALKIMIDVNDCKKWIIGKERGKNGYEHWQIR...
226,"(63, 71)",GWHVEDCVS,CAGTATTAC,MKYVATIPRDGIKESQLVRLLQTLDLHEAYLGREIGDGGYRHYQCA...
227,"(72, 80)",RAHWEPRRG,TAGTATTAC,MEHRKGRGTFSKDWVFTLNNYNEEDKELIEGIDCQYVIYGKEVGEN...
228,"(66, 74)",GWHVEECRD,TAGTATTAC,MITIDYILTIPRHSNPIKMVRCVLASVDAKKAIIGRELGQGGLDHW...

In [7]:
df_rep.to_csv('../data/processed/final_datasets/final_rep_dataset.csv', index=False)

df_relax.to_csv('../data/processed/final_datasets/final_relax_dataset.csv', index=False)